version: '3.8'

services:
  focusflowblazor:
    build:
      context: .
      dockerfile: ./FocusFlow.Blazor/Dockerfile
    ports:
      - "9090:5000" # Expose Blazor app on HTTP port 8080
    depends_on:
      - focusflowwebapi

  focusflowwebapi:
    build:
      context: .
      dockerfile: ./FocusFlow.WebApi/Dockerfile
    ports:
      - "9091:5000" # Expose Web API on HTTP port 8081

networks:
  default:
    driver: bridge